# Generated by Django 4.0 on 2023-10-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('studentId', models.CharField(blank=True, max_length=10, unique=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('register_year', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('lecture', models.CharField(blank=True, choices=[('CB', '計算機概論'), ('student', '計算機網路'), ('engineer', '微積分'), ('developer', '線性代數'), ('designer', '離散數學'), ('accountant', '程式設計')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
