# Generated by Django 4.0 on 2023-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lecture',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, choices=[('IC', '計算機概論'), ('CN', '計算機網路'), ('C', '微積分'), ('LN', '線性代數'), ('DM', '離散數學'), ('P', '程式設計')], max_length=100, null=True),
        ),
    ]
