# Generated by Django 4.0 on 2023-10-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mission_missioncategory_missionrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='alias',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(),
        ),
    ]
